export PS1="\u@\h:\w \$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/')\n\\$\[$(tput sgr0)\]"

source ~/usr/share/alias
. "$HOME/.cargo/env"
export UBIN="$HOME/usr/bin"
export PATH="$UBIN:$PATH"
